### ISSUE TITLE
Bug with ++ and --

### ISSUE THREAD

**Issue by dbbutcher1** [dbbutcher1/cox-karma-bot#5]
A bug exists when adding or removing karma without a name.

When passing ------
<@> gets negative karma

When passing +++++
an error occurs

**Comment by otakujonn** [comment]
following also throws an error Jonathan Nathan
[10:31 AM] 
@test. --

cox-karmaAPP [10:31 AM] 
@jn :poop:! We encountered an error :cry:!!!>

**Comment by otakujonn** [comment]
corrected in dev
